"""
Django settings for musical_academy project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import os
from urllib.parse import quote_plus

from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

def env_bool(name, default=False):
    return os.getenv(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    return [
        item.strip().rstrip('/')
        for item in os.getenv(name, default).split(',')
        if item.strip()
    ]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', False)

# SECURITY WARNING: keep the secret key used in production secret.
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-2+zeyp+_=28(&erw05lw%)a_7f9&j$+exooy*q1fycju^wh)$c')
if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    raise ImproperlyConfigured('Set a strong SECRET_KEY when DEBUG=False.')

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1,0.0.0.0')

# CORS Configuration - accepts comma-separated origins:
# FRONTEND_URL=https://app.tma.ma,https://statuesque-cajeta-aed5c5.netlify.app
_frontend_origins = env_list('FRONTEND_URL') + env_list('FRONTEND_URLS')
_cors_origins = env_list('CORS_ALLOWED_ORIGINS')
CORS_ALLOWED_ORIGINS = list(dict.fromkeys([
    'http://localhost:3000',
    *_frontend_origins,
    *_cors_origins,
]))
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS') or CORS_ALLOWED_ORIGINS

# Allow credentials for cross-origin requests
CORS_ALLOW_CREDENTIALS = True

AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
    'users.authentication.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_celery_results',
    'django_celery_beat',
    'users',
    'academics',
    'enrollments',
    'planning',
    'finances',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Production security. Local development remains HTTP-friendly when DEBUG=True.
SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', not DEBUG)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', not DEBUG)
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', not DEBUG)
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000' if not DEBUG else '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', not DEBUG)
SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', False)
if env_bool('SECURE_PROXY_SSL_HEADER', not DEBUG):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

ROOT_URLCONF = 'musical_academy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'musical_academy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
    }
}

# Handle SQLite vs PostgreSQL
if DATABASES['default']['ENGINE'] == 'postgresql':
    DATABASES['default']['ENGINE'] = 'django.db.backends.postgresql'
elif DATABASES['default']['ENGINE'] == 'django.db.backends.sqlite3':
    # For SQLite, NAME should be a Path object
    if not isinstance(DATABASES['default']['NAME'], Path):
        DATABASES['default']['NAME'] = BASE_DIR / 'db.sqlite3'


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Course Offer configuration is now stored in the DB via the AcademySettings model.
# Use the Settings page in the frontend dashboard to configure it at runtime.
# The values below are only used as a LAST-RESORT fallback if the DB row has
# never been initialised (e.g. fresh install before first migration).
COURSE_OFFER_FALLBACK = {
    'enabled': False,
    'free_course_id': None,
    'max_times': 1,
}

def build_celery_sql_broker_url():
    """
    Use the same database as Celery broker when CELERY_BROKER_URL is not set.
    PostgreSQL is recommended for this mode; SQLite is only acceptable locally.
    """
    database = DATABASES['default']
    engine = database['ENGINE']
    if engine == 'django.db.backends.sqlite3':
        return f"sqla+sqlite:///{database['NAME']}"
    if engine == 'django.db.backends.postgresql':
        name = quote_plus(str(database['NAME']))
        user = quote_plus(str(database.get('USER') or ''))
        password = quote_plus(str(database.get('PASSWORD') or ''))
        host = str(database.get('HOST') or 'localhost')
        port = str(database.get('PORT') or '5432')
        auth = user
        if password:
            auth = f"{auth}:{password}"
        return f"sqla+postgresql://{auth}@{host}:{port}/{name}"
    return 'sqla+sqlite:///celery-broker.sqlite3'


# Redis-free Celery: SQLAlchemy broker queue + Django DB result backend.
# Run with:
#   celery -A musical_academy worker -l info
#   celery -A musical_academy beat -l info
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', build_celery_sql_broker_url())
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'django-db')
CELERY_CACHE_BACKEND = 'default'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = USE_TZ
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = int(os.getenv('CELERY_TASK_TIME_LIMIT', '1800'))
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BEAT_SCHEDULE = {
    'billing-daily-sync': {
        'task': 'academics.tasks.run_billing_automation',
        'schedule': 3600.0,
        'options': {'expires': 1800},
    },
}
