# Generated by Django 4.2.27 on 2026-01-20 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='end_date',
            field=models.DateField(blank=True, help_text='When this session plan ends (None = Indefinite)', null=True),
        ),
        migrations.CreateModel(
            name='SessionInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_date', models.DateField()),
                ('is_rescheduled', models.BooleanField(default=False)),
                ('new_date', models.DateField(blank=True, null=True)),
                ('new_start_time', models.TimeField(blank=True, null=True)),
                ('new_end_time', models.TimeField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='planning.classsession')),
                ('new_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.room')),
            ],
            options={
                'ordering': ['original_date'],
                'unique_together': {('class_session', 'original_date')},
            },
        ),
    ]
