# Generated by Codex for academic year support

from django.db import migrations, models
import django.db.models.deletion


def academic_year_for(value):
    start_year = value.year if value.month >= 9 else value.year - 1
    return start_year, start_year + 1


def get_or_create_year(AcademicYear, value):
    start_year, end_year = academic_year_for(value)
    obj, _ = AcademicYear.objects.get_or_create(
        name=f"{start_year}-{end_year}",
        defaults={
            'start_date': f"{start_year}-09-01",
            'end_date': f"{end_year}-08-31",
            'is_active': False,
        },
    )
    return obj


def populate_session_academic_year(apps, schema_editor):
    AcademicYear = apps.get_model('academics', 'AcademicYear')
    ClassSession = apps.get_model('planning', 'ClassSession')

    from django.utils import timezone

    today = timezone.now().date()
    for session in ClassSession.objects.all().iterator():
        year = get_or_create_year(AcademicYear, session.start_date or today)
        session.academic_year_id = year.id
        session.save(update_fields=['academic_year'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_academicyear_enrollment_year'),
        ('planning', '0003_sessioninstance_teacher_is_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='academics.academicyear'),
        ),
        migrations.RunPython(populate_session_academic_year, reverse_noop),
        migrations.AlterField(
            model_name='classsession',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='academics.academicyear'),
        ),
    ]
