# Generated by Django 4.2.27 on 2026-05-23 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_payment_notes_payment_subscription_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_studentprofile_address_studentprofile_age_group_and_more'),
        ('academics', '0007_academysettings_school_address_and_more'),
        ('planning', '0004_classsession_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherMonthlyPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('VALIDATED', 'Validated')], default='DRAFT', max_length=20)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('cancelled_sessions', models.PositiveIntegerField(default=0)),
                ('absent_sessions', models.PositiveIntegerField(default=0)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('worked_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_payrolls', to='academics.academicyear')),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_payroll', to='finances.expense')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_teacher_payrolls', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payrolls', to='users.teacherprofile')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_teacher_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month', 'teacher__user__last_name'],
                'unique_together': {('teacher', 'academic_year', 'year', 'month')},
            },
        ),
    ]
