# Generated by Django 4.2.27 on 2026-09-18 21:50

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_teachermonthlypayroll'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsession',
            options={'base_manager_name': 'all_objects', 'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.AlterModelManagers(
            name='classsession',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='classsession',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classsession',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
