# Generated by Django 4.2.27 on 2026-01-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-enrolled_at']},
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='is_active',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='custom_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual price charged (admin can override)', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Original course price at time of enrollment', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_promotional',
            field=models.BooleanField(default=False, help_text='Whether a promotional rule was suggested'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='promotional_reason',
            field=models.CharField(blank=True, help_text='Reason for promotional pricing', max_length=255),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly (3 months)')], default='MONTHLY', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount to be paid for this subscription period', max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='academics.enrollment')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
