# Generated by Django 4.2.27 on 2026-02-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_free_offer',
            field=models.BooleanField(default=False, help_text='Whether this enrollment was auto-added as a free offer course'),
        ),
    ]
