# Generated by Codex for academic year support

from django.db import migrations, models
from django.db.models import Q
import django.db.models.deletion


def academic_year_for(value):
    if hasattr(value, 'date'):
        value = value.date()
    start_year = value.year if value.month >= 9 else value.year - 1
    return start_year, start_year + 1


def get_or_create_year(AcademicYear, value, active=False):
    start_year, end_year = academic_year_for(value)
    obj, _ = AcademicYear.objects.get_or_create(
        name=f"{start_year}-{end_year}",
        defaults={
            'start_date': f"{start_year}-09-01",
            'end_date': f"{end_year}-08-31",
            'is_active': active,
        },
    )
    if active and not obj.is_active:
        AcademicYear.objects.exclude(pk=obj.pk).update(is_active=False)
        obj.is_active = True
        obj.save(update_fields=['is_active'])
    return obj


def populate_enrollment_academic_year(apps, schema_editor):
    AcademicYear = apps.get_model('academics', 'AcademicYear')
    Enrollment = apps.get_model('academics', 'Enrollment')

    from django.utils import timezone

    today = timezone.now().date()
    active_year = get_or_create_year(AcademicYear, today, active=True)

    for enrollment in Enrollment.objects.all().iterator():
        year = get_or_create_year(AcademicYear, enrollment.enrolled_at or today)
        enrollment.academic_year_id = year.id
        enrollment.save(update_fields=['academic_year'])

    if not AcademicYear.objects.filter(is_active=True).exists():
        active_year.is_active = True
        active_year.save(update_fields=['is_active'])


def reverse_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_academysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: 2025-2026', max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.academicyear'),
        ),
        migrations.RunPython(populate_enrollment_academic_year, reverse_noop),
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.academicyear'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'academic_year')},
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=Q(is_active=True), fields=('is_active',), name='only_one_active_academic_year'),
        ),
    ]
