# Generated by Django 4.2.27 on 2026-05-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_academicyear_enrollment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='academysettings',
            name='school_address',
            field=models.CharField(blank=True, default='à coté du café LE CAVALLI, Av. Taha Houcine, Fès 30050', max_length=255),
        ),
        migrations.AddField(
            model_name='academysettings',
            name='school_city',
            field=models.CharField(blank=True, default='Fès', max_length=100),
        ),
        migrations.AddField(
            model_name='academysettings',
            name='school_country',
            field=models.CharField(blank=True, default='Maroc', max_length=100),
        ),
        migrations.AddField(
            model_name='academysettings',
            name='school_description',
            field=models.TextField(blank=True, default='The Musical Academy est une école de musique proposant des cours pour tous les niveaux et tous les âges.'),
        ),
        migrations.AddField(
            model_name='academysettings',
            name='school_email',
            field=models.EmailField(blank=True, default='contact@themusicalacademy.net', max_length=254),
        ),
        migrations.AddField(
            model_name='academysettings',
            name='school_name',
            field=models.CharField(default='The Musical Academy', max_length=255),
        ),
        migrations.AddField(
            model_name='academysettings',
            name='school_phone',
            field=models.CharField(blank=True, default='+212 695-969711', max_length=50),
        ),
        migrations.AddField(
            model_name='academysettings',
            name='school_postal_code',
            field=models.CharField(blank=True, default='30050', max_length=20),
        ),
        migrations.AddField(
            model_name='academysettings',
            name='school_tax_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
