# Generated by Django 4.2.27 on 2026-05-25

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations, models


def backfill_billing_plan_and_monthly_price(apps, schema_editor):
    Enrollment = apps.get_model('academics', 'Enrollment')
    Subscription = apps.get_model('academics', 'Subscription')

    for enrollment in Enrollment.objects.all().iterator():
        latest_subscription = (
            Subscription.objects
            .filter(enrollment_id=enrollment.id)
            .order_by('-end_date', '-start_date', '-id')
            .first()
        )
        if not latest_subscription:
            continue

        enrollment.billing_plan = latest_subscription.subscription_type

        # Before this migration, the frontend stored the quarterly period total
        # in Enrollment.custom_price. From now on custom_price is the monthly base.
        if (
            latest_subscription.subscription_type == 'QUARTERLY'
            and enrollment.custom_price
            and latest_subscription.amount == enrollment.custom_price
        ):
            enrollment.custom_price = (enrollment.custom_price / Decimal('3')).quantize(
                Decimal('0.01'),
                rounding=ROUND_HALF_UP,
            )

        enrollment.save(update_fields=['billing_plan', 'custom_price'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_academysettings_school_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='billing_plan',
            field=models.CharField(
                choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly (3 months)')],
                default='MONTHLY',
                help_text='Plan used for future automatic subscription periods.',
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('enrollment', 'start_date', 'end_date')},
        ),
        migrations.RunPython(backfill_billing_plan_and_monthly_price, noop_reverse),
    ]
