# Generated by Django 4.2.27 on 2026-05-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_studentprofile_address_studentprofile_age_group_and_more'),
        ('academics', '0008_billing_plan_and_subscription_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='academysettings',
            name='default_insurance_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='academysettings',
            name='default_registration_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('REGISTRATION', 'Registration fee'), ('INSURANCE', 'Insurance')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('EXEMPT', 'Exempt')], default='PENDING', max_length=20)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fees', to='academics.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='users.studentprofile')),
            ],
            options={
                'ordering': ['due_date', 'fee_type'],
                'unique_together': {('student', 'academic_year', 'fee_type')},
            },
        ),
    ]
