# Generated by Django 4.2.27 on 2026-05-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_academysettings_default_insurance_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAutomationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100, unique=True)),
                ('is_running', models.BooleanField(default=False)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('last_result', models.JSONField(blank=True, default=dict)),
                ('run_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['job_name'],
            },
        ),
        migrations.CreateModel(
            name='BillingAutomationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('ERROR', 'Error'), ('SKIPPED', 'Skipped')], max_length=20)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['job_name', '-started_at'], name='academics_b_job_nam_1c98c5_idx'), models.Index(fields=['status', '-started_at'], name='academics_b_status_935cba_idx')],
            },
        ),
    ]
