# Generated by Django 4.2.27 on 2026-01-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_enrollment_options_remove_enrollment_is_active_and_more'),
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, help_text='Link to subscription (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='academics.subscription'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CARD', 'Credit Card'), ('TRANSFER', 'Bank Transfer'), ('CASH', 'Cash'), ('CHECK', 'Check')], max_length=20),
        ),
    ]
