# Generated by Django 4.2.27 on 2026-05-30 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_academysettings_default_insurance_fee_and_more'),
        ('finances', '0002_payment_notes_payment_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='student_fee',
            field=models.ForeignKey(blank=True, help_text='Link to one-time student fee (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='academics.studentfee'),
        ),
    ]
