# Generated by Django 4.2.27 on 2026-03-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('secretaire', 'Secrétaire')], default='admin', help_text='Role determines base access level', max_length=20),
        ),
    ]
